/**
 * File Name: LoginJFrame.java
 */

package lk.raneesh.csacwk.gui;

import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.BorderFactory;
import lk.raneesh.csacwk.controllers.UserController;

public class LoginJFrame extends javax.swing.JFrame {
    
    private RegistrationJFrame registration;
    private SelectThreadJFrame selectThreads;

    /**
     * Creates new form LoginJFrame
     */
    public LoginJFrame() {
        super("DRAGx Chat | Login");
        initComponents();
        setPlaceholder();
    }
    
    // Sets placeholder text to each field
    public void setPlaceholder() {
        chatHeaderLabel.requestFocus();
        
        loginIdText.setBorder(BorderFactory.createCompoundBorder(
        loginIdText.getBorder(), 
        BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        
        loginPasswordText.setBorder(BorderFactory.createCompoundBorder(
        loginPasswordText.getBorder(), 
        BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        
        loginIdText.setText("Enter Login ID...");
        loginIdText.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (loginIdText.getText().equals("Enter Login ID...")) {
                    loginIdText.setText("");
                    loginIdText.setForeground(Color.BLACK);
                }
            }
            @Override
            public void focusLost(FocusEvent e) {
                if (loginIdText.getText().isEmpty()) {
                    loginIdText.setForeground(Color.GRAY);
                    loginIdText.setText("Enter Login ID...");
                }
            }
        });
        
        loginPasswordText.setText("Enter Password...");
        loginPasswordText.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (loginPasswordText.getText().equals("Enter Password...")) {
                    loginPasswordText.setText("");
                    loginPasswordText.setForeground(Color.BLACK);
                }
            }
            @Override
            public void focusLost(FocusEvent e) {
                if (loginPasswordText.getText().isEmpty()) {
                    loginPasswordText.setForeground(Color.GRAY);
                    loginPasswordText.setText("Enter Password...");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        chatHeaderLabel = new javax.swing.JLabel();
        loginIdText = new javax.swing.JTextField();
        loginBtn = new javax.swing.JButton();
        loginRegisterBtn = new javax.swing.JButton();
        loginPasswordText = new javax.swing.JPasswordField();
        regQueryTextLabel = new javax.swing.JLabel();
        passwordPromptLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        loginPanel.setBackground(new java.awt.Color(0, 0, 0));
        loginPanel.setForeground(new java.awt.Color(255, 255, 255));

        chatHeaderLabel.setFont(new java.awt.Font("Roboto Black", 0, 100)); // NOI18N
        chatHeaderLabel.setForeground(new java.awt.Color(153, 153, 0));
        chatHeaderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chatHeaderLabel.setText("DRAGx Chat");
        chatHeaderLabel.setToolTipText("");
        chatHeaderLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        loginIdText.setFont(new java.awt.Font("Poppins Light", 0, 14)); // NOI18N
        loginIdText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        loginIdText.setMargin(new java.awt.Insets(20, 20, 20, 20));

        loginBtn.setBackground(new java.awt.Color(102, 153, 0));
        loginBtn.setFont(new java.awt.Font("Roboto Light", 0, 20)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("LOGIN");
        loginBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginBtn.setBorderPainted(false);
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        loginRegisterBtn.setBackground(new java.awt.Color(0, 51, 51));
        loginRegisterBtn.setFont(new java.awt.Font("Roboto Light", 0, 17)); // NOI18N
        loginRegisterBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginRegisterBtn.setText("Register");
        loginRegisterBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginRegisterBtn.setBorderPainted(false);
        loginRegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginRegisterBtnActionPerformed(evt);
            }
        });

        loginPasswordText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        loginPasswordText.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        regQueryTextLabel.setForeground(new java.awt.Color(255, 255, 255));
        regQueryTextLabel.setText("Don't have an account ?");

        passwordPromptLabel.setBackground(new java.awt.Color(0, 0, 0));
        passwordPromptLabel.setForeground(new java.awt.Color(153, 153, 0));
        passwordPromptLabel.setText("* Enter Password");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(regQueryTextLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginRegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(loginPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(passwordPromptLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(loginIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(chatHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(chatHeaderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(loginIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordPromptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regQueryTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginRegisterBtn))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginRegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginRegisterBtnActionPerformed
        registration = new RegistrationJFrame();
        registration.setVisible(true);
        this.setVisible(false);
        //dispose();
    }//GEN-LAST:event_loginRegisterBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String username = loginIdText.getText();
        char[] password = loginPasswordText.getText().toCharArray(); 
        
        // Sends to web client for validation and if so logging in of user
        boolean isLoginSuccessful = UserController.loginUser(username, password);
        
        loginIdText.setText("");
        loginPasswordText.setText("");
        
        if (isLoginSuccessful) {
           selectThreads = new SelectThreadJFrame();
           selectThreads.setVisible(true);
           this.setVisible(false); 
        }        
    }//GEN-LAST:event_loginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chatHeaderLabel;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField loginIdText;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField loginPasswordText;
    private javax.swing.JButton loginRegisterBtn;
    private javax.swing.JLabel passwordPromptLabel;
    private javax.swing.JLabel regQueryTextLabel;
    // End of variables declaration//GEN-END:variables
}
