/**
 * File Name: ThreadPanel.java
 */

package lk.raneesh.csacwk.gui.customlist;

import java.awt.Component;
import javax.swing.JList;
import javax.swing.ListCellRenderer;
import lk.raneesh.csacwk.datastructure.ThreadList;

public class ThreadPanel extends javax.swing.JPanel implements ListCellRenderer<ThreadList> {

    /**
     * Creates new form MessagePanel
     */
    public ThreadPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        threadPanel = new javax.swing.JPanel();
        threadTitleListLabel = new javax.swing.JLabel();
        threadCreatorListLabel = new javax.swing.JLabel();
        threadDateListLabel = new javax.swing.JLabel();
        createdByLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        threadTitleListLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        threadTitleListLabel.setText("Thread Title");

        threadCreatorListLabel.setText("Thread Creator");

        threadDateListLabel.setText("Thread Date");

        createdByLabel.setText("Last Edited:");

        javax.swing.GroupLayout threadPanelLayout = new javax.swing.GroupLayout(threadPanel);
        threadPanel.setLayout(threadPanelLayout);
        threadPanelLayout.setHorizontalGroup(
            threadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(threadPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(threadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(threadPanelLayout.createSequentialGroup()
                        .addComponent(createdByLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(threadCreatorListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(threadDateListLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                    .addComponent(threadTitleListLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        threadPanelLayout.setVerticalGroup(
            threadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(threadPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(threadTitleListLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(threadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(threadCreatorListLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(threadDateListLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createdByLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(threadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(threadPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createdByLabel;
    private javax.swing.JLabel threadCreatorListLabel;
    private javax.swing.JLabel threadDateListLabel;
    private javax.swing.JPanel threadPanel;
    private javax.swing.JLabel threadTitleListLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public Component getListCellRendererComponent(JList<? extends ThreadList> list, ThreadList value, int index, boolean isSelected, boolean cellHasFocus) {
        // Each swing component is assigned a value when executed through the getters of the respective list class
        this.threadTitleListLabel.setText(value.getThreadTitle());
        this.threadCreatorListLabel.setText(value.getThreadCreator());
        this.threadDateListLabel.setText(value.getThreadDate());
        
        return this;
    }

    
}
